resolver: lts-20.26

flags: {}

extra-include-dirs:
- ../../.local/lib/hasktorch/deps/libtorch/include/torch/csrc/api/include
- ../../.local/lib/hasktorch/deps/libtorch/include

extra-lib-dirs:
- ../../.local/lib/hasktorch/deps/libtorch/lib
- ../../.local/lib/hasktorch/deps/libtokenizers/lib
- ../../.local/lib/hasktorch/deps/mklml/lib

extra-deps:
- ../../.local/lib/hasktorch/codegen
- ../../.local/lib/hasktorch/libtorch-ffi
- ../../.local/lib/hasktorch/libtorch-ffi-helper
- ../../.local/lib/hasktorch/hasktorch
- ../../.local/lib/hasktorch-tools
- inline-c-0.9.1.10
- inline-c-cpp-0.5.0.2
- git: http://github.com/DaisukeBekki/JSeM
  commit: c2cd39168e267007b4690dbf625329bac57a8185
- git: http://github.com/DaisukeBekki/nlp-tools
  commit: e4bd3783f4e872b8df29538d9219e41f40378363
- random-shuffle-0.0.4
- sqlite-simple-0.4.19.0
# 1bf4e582c603c823a89c3dfd1fba0ab4d3d8899a
#  - git: git@github.com:DaisukeBekki/hasktorch-tools.git
#    commit: 936928cdee27e179a5e3775d146046b107b0eba1
# - json-stream-0.4.4.2@sha256:f840c692db1f47f6d6b08c56fc0ba0a567be426b9ae9e6739fe73d52136e6d91,4985
# - git: https://github.com/fpco/inline-c
#   commit: 2d0fe9b2f0aa0e1aefc7bfed95a501e59486afb0
#   subdirs:
#   - inline-c
# - git: https://github.com/fpco/inline-c
#   commit: 2d0fe9b2f0aa0e1aefc7bfed95a501e59486afb0
#   subdirs:
#   - inline-c-cpp

allow-newer: true

build:
  haddock: false
  haddock-arguments:
    haddock-args:
    - --odir=haddock
  open-haddocks: false
  haddock-internal: false
  haddock-hyperlink-source: true

